config/routes.rb
Restfulapp::Application.routes.draw do
  
  resources :users do
    resources :posts
  end
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.where(params[:id]).destroy
    if @user.destroy
      flash[:notice] = "User #{@user.email} destroyed"
    else
      flash[:alert] = "There was a problem destroying the user."
    end
    redirect_to "/user"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restfulapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>The list below is all the Posts.</h1>

<% @posts.each do |post| %>
  <div>
    <p>Title: <%= post.title %></p>
    <p>Post: <%= post.body %></p>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>The list below is all the Users.</h1>

<% @users.each do |user| %>
  <div>
    <p>Names: <%= user.fname + ' ' + user.lname %></p>
    <p>Email: <%= user.email  %></p>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Please view the display of the User below:</h1>

<div>
  <h1><%= @user.fname %></h1>
  <h1><%= @user.lname %></h1>
  <h1><%= @user.email %></h1>
 
  <%= link_to "Delete User", user_path(1), {method: :delete} %>
</div>